### ISSUE TITLE
Header is too short on mobiles.

### ISSUE THREAD

**Issue by bearbin** [cuberite/plugin-repository#19]
![image](https://cloud.githubusercontent.com/assets/1297699/15633648/ad775780-25aa-11e6-9b48-0ec57bc7d743.png)

**Comment by bearbin** [comment]
There are also random spaces in between plugins, which should be fixed.

**Comment by NiLSPACE** [comment]
This is also happening with a desktop. Most likely due to "version: 1"

**Comment by bearbin** [comment]
I fixed the random spaces, but the header is still in need of improvement.

**Comment by tigerw** [comment]
To be honest, I think your revered chrome browser is displaying it wrong. The spacing between the tiles is not meant to look like that, and it doesn't on IE or Edge.

Anyways, I'm thinking of using the flexible box model instead.

**Comment by NiLSPACE** [comment]
It's also happening on Firefox.

**Comment by tigerw** [comment]
The header is definitely broken, and broken because I have no idea how to style properly. I was just whining about the irregular spacings. The latter should be somewhat improved now - I changed it to use the flexbox.

**Comment by tigerw** [comment]
The new styling has improved on this, could you please confirm?

**Comment by bearbin** [comment]
This was fixed in the recent redesign.
