### ISSUE TITLE
Alpha-sort lists

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/plugin-repository#35]
Lists on the site should be alpha-sorted:
- [x] Repositories in "Add plugin"
- [x] Organizations in "Add plugin"

**Comment by tigerw** [comment]
How about now?

**Comment by madmaxoft** [comment]
Doesn't seem so...
![image](https://user-images.githubusercontent.com/4388386/77828635-f021ee80-711c-11ea-8109-e610284c7f63.png)

**Comment by bearbin** [comment]
Alpha-sorting the homepage doesn't make sense at all, otherwise we end up with a 009 sound system situation (or equivalently "A1 {x} Plugin")

**Comment by madmaxoft** [comment]
Okay, I mis-read the topic. The repos are sorted when adding a new plugin, but it seems they are truncated, mine shows only repositories M to Z

**Comment by tigerw** [comment]
Thanks. Pagination support tracked in #36.
