### ISSUE TITLE
Plugins should be able to specify their license. 

### ISSUE THREAD

**Issue by bearbin** [cuberite/plugin-repository#4]
Also recommend that plugins choose a FOSS license when they upload.

**Comment by tigerw** [comment]
I guess that's now handled by GitHub. Close?

**Comment by bearbin** [comment]
In fact, we should require that plugins provide a license that allows for free use and redistribution, as a protection for users.

**Comment by tigerw** [comment]
GitHub introduced a new licenses API. Do you suggest that we check that repositories a license with the `private-use` and `distribution` allowances? Should we outright deny those with unrecognised licenses?

**Comment by bearbin** [comment]
Fixed. No need for additional complexity/confusion by denying unrecognised licenses.
