### ISSUE TITLE
Plugin downloads don't work

### ISSUE THREAD

**Issue by mathiascode** [cuberite/plugin-repository#44]
When attempting to download plugins, the following message appears:
`ERROR: Unable to connect to MySQL server! Error: Access denied for user 'bde5006a4f0235'@'104.41.1.8' (using password: YES)`
@tigerw

**Comment by misaalanshori** [comment]
when will this error be fixed?
![image](https://user-images.githubusercontent.com/38964181/45595810-8e3ae180-b9db-11e8-82c7-37cb0ce750c6.png)

Can someone send a direct download link or a mirror i can use?

**Comment by mathiascode** [comment]
Any update on this? @tigerw

**Comment by tigerw** [comment]
Should be fixed.
