### ISSUE TITLE
Repo should use new cuberite logo.

### ISSUE THREAD

**Issue by bearbin** [cuberite/plugin-repository#5]

**Comment by NiLSPACE** [comment]
Do we have a logo that most people agree on?

**Comment by bearbin** [comment]
I think this one is pretty much agreed. But maybe I'm mistaken.

![cuberite2 1](https://cloud.githubusercontent.com/assets/1297699/7735036/66ea26c0-ff32-11e4-89d3-2f880bccfd63.png)

**Comment by NiLSPACE** [comment]
I like the cube on the forum allot.
![-](http://puu.sh/hUx2U/8cf2d817eb.jpg)

**Comment by bearbin** [comment]
For me, that's generic and web-2.0y. But if everyone else thinks it's the best logo then maybe we should use that. We should have a vote somewhere.

**Comment by tigerw** [comment]
As I said, since its a repository for MCS plugins, why solely have the logo of the Cuberite organisations?

**Comment by bearbin** [comment]
The logo is designed to be both the organisation and the server.

**Comment by tigerw** [comment]
Though the server logo isn't changing.

**Comment by bearbin** [comment]
Huh?

**Comment by tigerw** [comment]
The Cuberite logo may be applicable for both server and organisation, but if the server logo is still staying the same, presumably that is the default for everything server-related.

**Comment by bearbin** [comment]
I made a proposal: https://github.com/mc-server/MCServer/issues/2090

**Comment by bearbin** [comment]
This was fixed.
