### ISSUE TITLE
Support BB-code

### ISSUE THREAD

**Issue by NiLSPACE** [cuberite/plugin-repository#6]
If we'd let the plugin repo support BB code then we could use the output from the [InfoDump](https://github.com/cuberite/cuberite/blob/master/Server/Plugins/InfoDump.lua) file directly. It shouldn't be too hard to implement:

``` php
function HandleBBCode($a_Text)
{
  $patterns = array(
   '~\[b\](.*?)\[/b\]~',
   '~\[color=(\w*?)\](.*)\[/color\]',
   // Other patterns
  );

  $results = array(
   '<b>$1</b>',
   '<span style="color:$1;">$2</span>',
   // Other results
  );

  return preg_replace($patterns, $results, $a_Text);
}
```

**Comment by tigerw** [comment]
The plan is to basically offload everything, including description storage (probably as a README.md), onto GitHub. If this is to happen, it may become necessary for InfoDump to output Markdown since ideally the forum will no longer be the place to store plugins.

**Comment by NiLSPACE** [comment]
The InfoDump already dumps both BB-code and markdown, so it shouldn't be a problem. Personally I like BB-code more than markdown, so that's why I suggested it here ;)
